/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* src = "design.sv:1.1-36.10" *)
module syn_fifo(clk, rst, wrt_en, rd_en, data_in, empty, full, data_out);
  (* src = "design.sv:25.3-35.6" *)
  wire [7:0] _00_;
  (* src = "design.sv:21.17-21.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _01_;
  (* src = "design.sv:33.17-33.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _02_;
  (* src = "design.sv:7.19-7.32" *)
  wire [2:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "design.sv:19.13-19.28" *)
  wire _12_;
  (* src = "design.sv:31.13-31.28" *)
  wire _13_;
  (* src = "design.sv:19.23-19.28" *)
  wire _14_;
  (* src = "design.sv:31.22-31.28" *)
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "design.sv:1.23-1.26" *)
  input clk;
  wire clk;
  (* src = "design.sv:1.64-1.71" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "design.sv:1.108-1.116" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "design.sv:1.80-1.85" *)
  output empty;
  wire empty;
  (* src = "design.sv:1.87-1.91" *)
  output full;
  wire full;
  (* src = "design.sv:10.11-10.12" *)
  wire [31:0] i;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[0] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[1] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[2] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[3] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[4] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[5] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[6] ;
  (* src = "design.sv:3.12-3.15" *)
  reg [7:0] \mem[7] ;
  (* src = "design.sv:1.47-1.52" *)
  input rd_en;
  wire rd_en;
  (* src = "design.sv:5.13-5.19" *)
  reg [2:0] rd_ptr = 3'h0;
  (* src = "design.sv:1.34-1.37" *)
  input rst;
  wire rst;
  (* src = "design.sv:4.13-4.19" *)
  reg [2:0] wr_ptr = 3'h0;
  (* src = "design.sv:1.39-1.45" *)
  input wrt_en;
  wire wrt_en;
  assign _01_ = wr_ptr + (* src = "design.sv:21.17-21.27" *) 32'd1;
  assign _02_ = rd_ptr + (* src = "design.sv:33.17-33.27" *) 32'd1;
  assign _03_ = wr_ptr + (* src = "design.sv:7.19-7.32" *) 1'h1;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[7]  <= 8'h00;
    else if (_04_) \mem[7]  <= data_in;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[2]  <= 8'h00;
    else if (_05_) \mem[2]  <= data_in;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[3]  <= 8'h00;
    else if (_06_) \mem[3]  <= data_in;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[4]  <= 8'h00;
    else if (_07_) \mem[4]  <= data_in;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[5]  <= 8'h00;
    else if (_08_) \mem[5]  <= data_in;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[6]  <= 8'h00;
    else if (_09_) \mem[6]  <= data_in;
  (* src = "design.sv:25.3-35.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) data_out <= 8'h00;
    else if (_13_) data_out <= _00_;
  (* src = "design.sv:25.3-35.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) rd_ptr <= 3'h0;
    else if (_13_) rd_ptr <= _02_[2:0];
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) wr_ptr <= 3'h0;
    else if (_12_) wr_ptr <= _01_[2:0];
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[0]  <= 8'h00;
    else if (_10_) \mem[0]  <= data_in;
  (* src = "design.sv:12.3-23.6" *)
  always @(posedge clk, negedge rst)
    if (!rst) \mem[1]  <= 8'h00;
    else if (_11_) \mem[1]  <= data_in;
  assign _04_ = & { _27_, _12_ };
  assign _05_ = & { _16_, _12_ };
  assign _06_ = & { _31_, _12_ };
  assign _07_ = & { _30_, _12_ };
  assign _08_ = & { _29_, _12_ };
  assign _09_ = & { _28_, _12_ };
  assign _10_ = & { _18_, _12_ };
  assign _11_ = & { _17_, _12_ };
  assign full = _03_ == (* src = "design.sv:7.18-7.41" *) rd_ptr;
  assign empty = wr_ptr == (* src = "design.sv:8.19-8.33" *) rd_ptr;
  assign _12_ = wrt_en && (* src = "design.sv:19.13-19.28" *) _14_;
  assign _13_ = rd_en && (* src = "design.sv:31.13-31.28" *) _15_;
  assign _14_ = ! (* src = "design.sv:19.23-19.28" *) full;
  assign _15_ = ! (* src = "design.sv:31.22-31.28" *) empty;
  assign _16_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h2;
  assign _17_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h1;
  assign _18_ = ! (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) wr_ptr;
  function [7:0] _63_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "design.sv:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _63_ = b[7:0];
      8'b??????1?:
        _63_ = b[15:8];
      8'b?????1??:
        _63_ = b[23:16];
      8'b????1???:
        _63_ = b[31:24];
      8'b???1????:
        _63_ = b[39:32];
      8'b??1?????:
        _63_ = b[47:40];
      8'b?1??????:
        _63_ = b[55:48];
      8'b1???????:
        _63_ = b[63:56];
      default:
        _63_ = a;
    endcase
  endfunction
  assign _00_ = _63_(8'hxx, { \mem[0] , \mem[1] , \mem[2] , \mem[3] , \mem[4] , \mem[5] , \mem[6] , \mem[7]  }, { _26_, _25_, _24_, _23_, _22_, _21_, _20_, _19_ });
  assign _19_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h7;
  assign _20_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h6;
  assign _21_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h5;
  assign _22_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h4;
  assign _23_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h3;
  assign _24_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h2;
  assign _25_ = rd_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h1;
  assign _26_ = ! (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) rd_ptr;
  assign _27_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h7;
  assign _28_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h6;
  assign _29_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h5;
  assign _30_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h4;
  assign _31_ = wr_ptr == (* full_case = 32'd1 *) (* src = "design.sv:0.0-0.0" *) 3'h3;
  assign i = 32'd8;
endmodule
